services:
  kafka1:
    image: confluentinc/cp-kafka
    container_name: kks_power
    hostname: kafka
    ports:
      - "9091:9091"
      - "9092:9092"
    volumes:
      - ./sasl_server.properties:/etc/kafka/kraft/sasl_server.properties
      - ./kafka_server_jaas.conf:/etc/kafka/kraft/kafka_server_jaas.conf
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,BROKER:SASL_PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'SASL_PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT://:9091'
      KAFKA_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://localhost:9092,PLAINTEXT://localhost:9091'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'SASL_PLAINTEXT'

      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: 'PLAIN'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kraft/kafka_server_jaas.conf'

      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: '7NEQIl2aS5CUr4Bw6Cqy3g=='
